<?php
declare(strict_types=1);

// Vapi SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

VapiUtility::setRegistrar(function (VapiUtility $u): void {
    $u->clean = [VapiClean::class, 'call'];
    $u->done = [VapiDone::class, 'call'];
    $u->make_error = [VapiMakeError::class, 'call'];
    $u->feature_add = [VapiFeatureAdd::class, 'call'];
    $u->feature_hook = [VapiFeatureHook::class, 'call'];
    $u->feature_init = [VapiFeatureInit::class, 'call'];
    $u->fetcher = [VapiFetcher::class, 'call'];
    $u->make_fetch_def = [VapiMakeFetchDef::class, 'call'];
    $u->make_context = [VapiMakeContext::class, 'call'];
    $u->make_options = [VapiMakeOptions::class, 'call'];
    $u->make_request = [VapiMakeRequest::class, 'call'];
    $u->make_response = [VapiMakeResponse::class, 'call'];
    $u->make_result = [VapiMakeResult::class, 'call'];
    $u->make_point = [VapiMakePoint::class, 'call'];
    $u->make_spec = [VapiMakeSpec::class, 'call'];
    $u->make_url = [VapiMakeUrl::class, 'call'];
    $u->param = [VapiParam::class, 'call'];
    $u->prepare_auth = [VapiPrepareAuth::class, 'call'];
    $u->prepare_body = [VapiPrepareBody::class, 'call'];
    $u->prepare_headers = [VapiPrepareHeaders::class, 'call'];
    $u->prepare_method = [VapiPrepareMethod::class, 'call'];
    $u->prepare_params = [VapiPrepareParams::class, 'call'];
    $u->prepare_path = [VapiPreparePath::class, 'call'];
    $u->prepare_query = [VapiPrepareQuery::class, 'call'];
    $u->graphql_body = [VapiGraphql::class, 'body'];
    $u->graphql_errors = [VapiGraphql::class, 'errors'];
    $u->result_basic = [VapiResultBasic::class, 'call'];
    $u->result_body = [VapiResultBody::class, 'call'];
    $u->result_headers = [VapiResultHeaders::class, 'call'];
    $u->transform_request = [VapiTransformRequest::class, 'call'];
    $u->transform_response = [VapiTransformResponse::class, 'call'];
});
