

import Path from 'node:path'
import * as Fs from 'node:fs'

import { test, describe, afterEach } from 'node:test'
import assert from 'node:assert'
import { createLiveTransport } from '../../live-runner'
import { runLiveEntity } from '../../live-entity'


import { VapiSDK, BaseFeature, stdutil } from '../../..'

import {
  envOverride,
  liveClientOptions,
  liveDelay,
  loadEnvLocal,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
  maybeSkipControl,
} from '../../utility'


loadEnvLocal(__dirname + '/../../../.env.local')


describe('ChatEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when VAPI_TEST_LIVE=TRUE.
  afterEach(liveDelay('VAPI_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = VapiSDK.test()
    const ent = testsdk.Chat()
    assert(null != ent)
  })


  test('basic', async (t) => {

    const live = 'TRUE' === process.env.VAPI_TEST_LIVE
    for (const op of ['create', 'list', 'load', 'remove']) {
      if (!live && maybeSkipControl(t, 'entityOp', 'chat.' + op, live)) return
    }

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":{"assistant":{"a":true,"h":"Assistant","n":"assistant","r":false,"sh":"This is the assistant that will be used for the chat.","t":"`$ANY`","union":{"branches":23,"count":19650,"depth":53},"key$":"assistant","index$":0},"assistantId":{"a":true,"h":"Assistant Id","n":"assistantId","r":false,"sh":"This is the assistant that will be used for the chat.","t":"`$STRING`","key$":"assistantId","index$":1},"assistantOverrides":{"a":true,"h":"Assistant Overrides","n":"assistantOverrides","r":false,"sh":"These are the variable values that will be used to replace template variables in the assistant messages.","t":"`$ANY`","union":{"branches":23,"count":5356,"depth":37},"key$":"assistantOverrides","index$":2},"cost":{"a":true,"h":"Cost","n":"cost","r":false,"sh":"This is the cost of the chat in USD.","t":"`$NUMBER`","key$":"cost","index$":3},"costs":{"a":true,"h":"Costs","n":"costs","r":false,"sh":"These are the costs of individual components of the chat in USD.","t":"`$ARRAY`","union":{"branches":2,"count":1,"depth":1},"key$":"costs","index$":4},"createdAt":{"a":true,"fo":"date-time","h":"Created At","n":"createdAt","r":true,"sh":"This is the ISO 8601 date-time string of when the chat was created.","t":"`$STRING`","key$":"createdAt","index$":5},"id":{"a":true,"h":"Id","n":"id","r":true,"sh":"This is the unique identifier for the chat.","t":"`$STRING`","key$":"id","index$":6},"input":{"a":true,"h":"Input","n":"input","op":{"create":{"req":true,"type":"`$ANY`"}},"r":false,"sh":"This is the input text for the chat.","t":"`$ANY`","union":{"branches":5,"count":2,"depth":3},"key$":"input","index$":7},"messages":{"a":true,"h":"Messages","n":"messages","r":false,"sh":"This is an array of messages used as context for the chat.","t":"`$ARRAY`","union":{"branches":5,"count":1,"depth":1},"key$":"messages","index$":8},"name":{"a":true,"h":"Name","n":"name","r":false,"sh":"This is the name of the chat.","t":"`$STRING`","key$":"name","index$":9},"orgId":{"a":true,"h":"Org Id","n":"orgId","r":true,"sh":"This is the unique identifier for the org that this chat belongs to.","t":"`$STRING`","key$":"orgId","index$":10},"output":{"a":true,"h":"Output","n":"output","r":false,"sh":"This is the output messages generated by the system in response to the input.","t":"`$ARRAY`","union":{"branches":5,"count":1,"depth":1},"key$":"output","index$":11},"previousChatId":{"a":true,"h":"Previous Chat Id","n":"previousChatId","r":false,"sh":"This is the ID of the chat that will be used as context for the new chat.","t":"`$STRING`","key$":"previousChatId","index$":12},"sessionId":{"a":true,"h":"Session Id","n":"sessionId","r":false,"sh":"This is the ID of the session that will be used for the chat.","t":"`$STRING`","key$":"sessionId","index$":13},"squad":{"a":true,"h":"Squad","n":"squad","r":false,"sh":"This is the squad that will be used for the chat.","t":"`$ANY`","union":{"branches":23,"count":12463,"depth":49},"key$":"squad","index$":14},"squadId":{"a":true,"h":"Squad Id","n":"squadId","r":false,"sh":"This is the squad that will be used for the chat.","t":"`$STRING`","key$":"squadId","index$":15},"stream":{"a":true,"h":"Stream","n":"stream","r":false,"sh":"This is a flag that determines whether the response should be streamed.","t":"`$BOOLEAN`","key$":"stream","index$":16},"transport":{"a":true,"h":"Transport","n":"transport","r":false,"sh":"This is used to send the chat through a transport like SMS.","t":"`$ANY`","union":{"branches":23,"count":8908,"depth":45},"key$":"transport","index$":17},"updatedAt":{"a":true,"fo":"date-time","h":"Updated At","n":"updatedAt","r":true,"sh":"This is the ISO 8601 date-time string of when the chat was last updated.","t":"`$STRING`","key$":"updatedAt","index$":18}},"id":{"field":"id","name":"id"},"name":"chat","op":{"create":{"input":"data","name":"create","points":[{"a":true,"co":{"id":"POST /chat","source":"openapi3","version":2},"g":{},"k":"http","m":"POST","o":"/chat","q":{},"r":{},"s":[{"lit":"chat"}],"t":{"req":"`reqdata`","res":"`body`"},"index$":0},{"a":true,"co":{"id":"POST /chat/responses","source":"openapi3","version":2},"g":{},"k":"http","m":"POST","o":"/chat/responses","q":{"$action":"response"},"r":{},"s":[{"lit":"chat"},{"lit":"responses"}],"t":{"req":"`reqdata`","res":"`body`"},"index$":1}],"key$":"create"},"list":{"input":"data","name":"list","points":[{"a":true,"co":{"id":"GET /chat","source":"openapi3","version":2},"g":{"query":[{"a":true,"k":"query","n":"assistant_id","or":"assistantId","r":false,"t":"`$STRING`","index$":0},{"a":true,"ex":"assistant-1,assistant-2,assistant-3","k":"query","n":"assistant_id_any","or":"assistantIdAny","r":false,"t":"`$STRING`","index$":1},{"a":true,"k":"query","n":"created_at_ge","or":"createdAtGe","r":false,"t":"`$STRING`","index$":2},{"a":true,"k":"query","n":"created_at_gt","or":"createdAtGt","r":false,"t":"`$STRING`","index$":3},{"a":true,"k":"query","n":"created_at_le","or":"createdAtLe","r":false,"t":"`$STRING`","index$":4},{"a":true,"k":"query","n":"created_at_lt","or":"createdAtLt","r":false,"t":"`$STRING`","index$":5},{"a":true,"k":"query","n":"id","or":"id","r":false,"t":"`$STRING`","index$":6},{"a":true,"k":"query","n":"id_any","or":"idAny","r":false,"t":"`$STRING`","index$":7},{"a":true,"k":"query","n":"limit","or":"limit","r":false,"t":"`$NUMBER`","index$":8},{"a":true,"k":"query","n":"page","or":"page","r":false,"t":"`$NUMBER`","index$":9},{"a":true,"k":"query","n":"previous_chat_id","or":"previousChatId","r":false,"t":"`$STRING`","index$":10},{"a":true,"k":"query","n":"session_id","or":"sessionId","r":false,"t":"`$STRING`","index$":11},{"a":true,"k":"query","n":"sort_by","or":"sortBy","r":false,"t":"`$STRING`","index$":12},{"a":true,"k":"query","n":"sort_order","or":"sortOrder","r":false,"t":"`$STRING`","index$":13},{"a":true,"k":"query","n":"squad_id","or":"squadId","r":false,"t":"`$STRING`","index$":14},{"a":true,"k":"query","n":"updated_at_ge","or":"updatedAtGe","r":false,"t":"`$STRING`","index$":15},{"a":true,"k":"query","n":"updated_at_gt","or":"updatedAtGt","r":false,"t":"`$STRING`","index$":16},{"a":true,"k":"query","n":"updated_at_le","or":"updatedAtLe","r":false,"t":"`$STRING`","index$":17},{"a":true,"k":"query","n":"updated_at_lt","or":"updatedAtLt","r":false,"t":"`$STRING`","index$":18}]},"k":"http","m":"GET","o":"/chat","q":{"exist":["assistant_id","assistant_id_any","created_at_ge","created_at_gt","created_at_le","created_at_lt","id","id_any","limit","page","previous_chat_id","session_id","sort_by","sort_order","squad_id","updated_at_ge","updated_at_gt","updated_at_le","updated_at_lt"]},"r":{},"s":[{"lit":"chat"}],"t":{"req":"`reqdata`","res":"`body.results`"},"index$":0}],"key$":"list"},"load":{"input":"data","name":"load","points":[{"a":true,"co":{"id":"GET /chat/{id}","source":"openapi3","version":2},"g":{"params":[{"a":true,"k":"param","n":"id","or":"id","r":true,"t":"`$STRING`","index$":0}]},"k":"http","m":"GET","o":"/chat/{id}","q":{"exist":["id"]},"r":{},"s":[{"lit":"chat"},{"var":"id"}],"t":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"load"},"remove":{"input":"data","name":"remove","points":[{"a":true,"co":{"id":"DELETE /chat/{id}","source":"openapi3","version":2},"g":{"params":[{"a":true,"k":"param","n":"id","or":"id","r":true,"t":"`$STRING`","index$":0}]},"k":"http","m":"DELETE","o":"/chat/{id}","q":{"exist":["id"]},"r":{},"s":[{"lit":"chat"},{"var":"id"}],"t":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"remove"}},"relations":{"ancestors":[]},"key$":"chat","name__orig":"chat","Name":"Chat","name_":"chat","name-":"chat","NAME":"CHAT","index$":5}, {"active":true,"entity":"chat","key$":"BasicChatFlow","kind":"basic","name":"BasicChatFlow","param":{},"step":[{"a":true,"d":{},"i":{"ref":"chat_ref01"},"m":{},"o":"create","s":[],"v":[],"index$":0},{"a":true,"d":{},"i":{},"m":{},"o":"list","s":[],"v":[{"apply":"ItemExists","def":{"ref":"chat_ref01"}}],"index$":1},{"a":true,"d":{},"i":{"ref":"chat_ref01","srcdatavar":"chat_ref01_data","suffix":"_dt0"},"m":{"id":"chat01"},"o":"load","s":[],"v":[{"apply":"TextFieldMark","def":{"mark":"Mark01-chat_ref01"}}],"index$":2},{"a":true,"d":{},"i":{"ref":"chat_ref01","suffix":"_rm0"},"m":{"id":"chat01"},"o":"remove","s":[],"v":[],"index$":3},{"a":true,"d":{},"i":{"suffix":"_rt0"},"m":{},"o":"list","s":[],"v":[{"apply":"ItemNotExists","def":{"ref":"chat_ref01"}}],"index$":4}]}, 'Chat', {"POST /chat":{"protocol":"http","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","properties":{"assistantId":{"type":"string","description":"This is the assistant that will be used for the chat. To use an existing assistant, use `assistantId` instead.","key$":"assistantId"},"assistant":{"description":"This is the assistant that will be used for the chat. To use an existing assistant, use `assistantId` instead.","allOf":[{"type":"object","properties":{"transcriber":{},"model":{},"voice":{},"firstMessage":{},"firstMessageInterruptionsEnabled":{},"firstMessageMode":{},"voicemailDetection":{},"clientMessages":{},"serverMessages":{},"maxDurationSeconds":{},"backgroundSound":{},"modelOutputInMessagesEnabled":{},"transportConfigurations":{},"observabilityPlan":{},"credentials":{},"hooks":{},"name":{},"voicemailMessage":{},"endCallMessage":{},"endCallPhrases":{},"compliancePlan":{},"metadata":{},"backgroundSpeechDenoisingPlan":{},"analysisPlan":{},"artifactPlan":{},"startSpeakingPlan":{},"stopSpeakingPlan":{},"monitorPlan":{},"credentialIds":{},"server":{},"keypadInputPlan":{}},"x-ref":"#/components/schemas/CreateAssistantDTO"}],"key$":"assistant"},"assistantOverrides":{"description":"These are the variable values that will be used to replace template variables in the assistant messages.\nOnly variable substitution is supported in chat contexts - other assistant properties cannot be overridden.","allOf":[{"type":"object","properties":{"transcriber":{},"model":{},"voice":{},"firstMessage":{},"firstMessageInterruptionsEnabled":{},"firstMessageMode":{},"voicemailDetection":{},"clientMessages":{},"serverMessages":{},"maxDurationSeconds":{},"backgroundSound":{},"modelOutputInMessagesEnabled":{},"transportConfigurations":{},"observabilityPlan":{},"credentials":{},"hooks":{},"tools:append":{},"variableValues":{},"name":{},"voicemailMessage":{},"endCallMessage":{},"endCallPhrases":{},"compliancePlan":{},"metadata":{},"backgroundSpeechDenoisingPlan":{},"analysisPlan":{},"artifactPlan":{},"startSpeakingPlan":{},"stopSpeakingPlan":{},"monitorPlan":{},"credentialIds":{},"server":{},"keypadInputPlan":{}},"x-ref":"#/components/schemas/AssistantOverrides"}],"key$":"assistantOverrides"},"squadId":{"type":"string","description":"This is the squad that will be used for the chat. To use a transient squad, use `squad` instead.","key$":"squadId"},"squad":{"description":"This is the squad that will be used for the chat. To use an existing squad, use `squadId` instead.","allOf":[{"type":"object","properties":{"name":{},"members":{},"membersOverrides":{}},"required":["members"],"x-ref":"#/components/schemas/CreateSquadDTO"}],"key$":"squad"},"name":{"type":"string","description":"This is the name of the chat. This is just for your own reference.","maxLength":40,"key$":"name"},"sessionId":{"type":"string","description":"This is the ID of the session that will be used for the chat.\nMutually exclusive with previousChatId.","key$":"sessionId"},"input":{"description":"This is the input text for the chat.\nCan be a string or an array of chat messages.\nThis field is REQUIRED for chat creation.","oneOf":[{"type":"string","title":"String"},{"type":"array","items":{"oneOf":[]},"title":"MessageArray"}],"examples":["Hello, how can you help me?",[{"role":"user","content":"Hello, how can you help me?"}]],"key$":"input"},"stream":{"type":"boolean","description":"This is a flag that determines whether the response should be streamed.\nWhen true, the response will be sent as chunks of text.","default":false,"key$":"stream"},"previousChatId":{"type":"string","description":"This is the ID of the chat that will be used as context for the new chat.\nThe messages from the previous chat will be used as context.\nMutually exclusive with sessionId.","key$":"previousChatId"},"transport":{"description":"This is used to send the chat through a transport like SMS.\nIf transport.phoneNumberId and transport.customer are provided, creates a new session.\nIf sessionId is provided without transport fields, uses existing session data.\nCannot specify both sessionId and transport fields (phoneNumberId/customer) together.","allOf":[{"type":"object","properties":{"conversationType":{},"phoneNumberId":{},"customer":{},"customerId":{},"useLLMGeneratedMessageForOutbound":{},"type":{}},"required":["type"],"x-ref":"#/components/schemas/TwilioSMSChatTransport"}],"key$":"transport"}},"required":["input"],"x-ref":"#/components/schemas/CreateChatDTO","index$":1}}}},"parameters":[]},"POST /chat/responses":{"protocol":"http","requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object","properties":{"assistantId":{"type":"string","description":"This is the assistant that will be used for the chat. To use an existing assistant, use `assistantId` instead."},"assistant":{"description":"This is the assistant that will be used for the chat. To use an existing assistant, use `assistantId` instead.","allOf":[{"type":"object","properties":{"transcriber":{},"model":{},"voice":{},"firstMessage":{},"firstMessageInterruptionsEnabled":{},"firstMessageMode":{},"voicemailDetection":{},"clientMessages":{},"serverMessages":{},"maxDurationSeconds":{},"backgroundSound":{},"modelOutputInMessagesEnabled":{},"transportConfigurations":{},"observabilityPlan":{},"credentials":{},"hooks":{},"name":{},"voicemailMessage":{},"endCallMessage":{},"endCallPhrases":{},"compliancePlan":{},"metadata":{},"backgroundSpeechDenoisingPlan":{},"analysisPlan":{},"artifactPlan":{},"startSpeakingPlan":{},"stopSpeakingPlan":{},"monitorPlan":{},"credentialIds":{},"server":{},"keypadInputPlan":{}},"x-ref":"#/components/schemas/CreateAssistantDTO"}]},"assistantOverrides":{"description":"These are the variable values that will be used to replace template variables in the assistant messages.\nOnly variable substitution is supported in chat contexts - other assistant properties cannot be overridden.","allOf":[{"type":"object","properties":{"transcriber":{},"model":{},"voice":{},"firstMessage":{},"firstMessageInterruptionsEnabled":{},"firstMessageMode":{},"voicemailDetection":{},"clientMessages":{},"serverMessages":{},"maxDurationSeconds":{},"backgroundSound":{},"modelOutputInMessagesEnabled":{},"transportConfigurations":{},"observabilityPlan":{},"credentials":{},"hooks":{},"tools:append":{},"variableValues":{},"name":{},"voicemailMessage":{},"endCallMessage":{},"endCallPhrases":{},"compliancePlan":{},"metadata":{},"backgroundSpeechDenoisingPlan":{},"analysisPlan":{},"artifactPlan":{},"startSpeakingPlan":{},"stopSpeakingPlan":{},"monitorPlan":{},"credentialIds":{},"server":{},"keypadInputPlan":{}},"x-ref":"#/components/schemas/AssistantOverrides"}]},"squadId":{"type":"string","description":"This is the squad that will be used for the chat. To use a transient squad, use `squad` instead."},"squad":{"description":"This is the squad that will be used for the chat. To use an existing squad, use `squadId` instead.","allOf":[{"type":"object","properties":{"name":{},"members":{},"membersOverrides":{}},"required":["members"],"x-ref":"#/components/schemas/CreateSquadDTO"}]},"name":{"type":"string","description":"This is the name of the chat. This is just for your own reference.","maxLength":40},"sessionId":{"type":"string","description":"This is the ID of the session that will be used for the chat.\nMutually exclusive with previousChatId."},"input":{"description":"This is the input text for the chat.\nCan be a string or an array of chat messages.\nThis field is REQUIRED for chat creation.","oneOf":[{"type":"string","title":"String"},{"type":"array","items":{"oneOf":[]},"title":"MessageArray"}],"examples":["Hello, how can you help me?",[{"role":"user","content":"Hello, how can you help me?"}]]},"stream":{"type":"boolean","description":"Whether to stream the response or not.","default":true},"previousChatId":{"type":"string","description":"This is the ID of the chat that will be used as context for the new chat.\nThe messages from the previous chat will be used as context.\nMutually exclusive with sessionId."},"transport":{"description":"This is used to send the chat through a transport like SMS.\nIf transport.phoneNumberId and transport.customer are provided, creates a new session.\nIf sessionId is provided without transport fields, uses existing session data.\nCannot specify both sessionId and transport fields (phoneNumberId/customer) together.","allOf":[{"type":"object","properties":{"conversationType":{},"phoneNumberId":{},"customer":{},"customerId":{},"useLLMGeneratedMessageForOutbound":{},"type":{}},"required":["type"],"x-ref":"#/components/schemas/TwilioSMSChatTransport"}]}},"required":["input"],"x-ref":"#/components/schemas/OpenAIResponsesRequest"}}}},"parameters":[]},"GET /chat":{"protocol":"http","parameters":[{"name":"id","required":false,"in":"query","description":"This is the unique identifier for the chat to filter by.","schema":{"type":"string"},"index$":0},{"name":"assistantId","required":false,"in":"query","description":"This is the unique identifier for the assistant that will be used for the chat.","schema":{"type":"string"},"index$":1},{"name":"assistantIdAny","required":false,"in":"query","description":"Filter by multiple assistant IDs. Provide as comma-separated values.","schema":{"example":"assistant-1,assistant-2,assistant-3","type":"string"},"index$":2},{"name":"squadId","required":false,"in":"query","description":"This is the unique identifier for the squad that will be used for the chat.","schema":{"type":"string"},"index$":3},{"name":"sessionId","required":false,"in":"query","description":"This is the unique identifier for the session that will be used for the chat.","schema":{"type":"string"},"index$":4},{"name":"previousChatId","required":false,"in":"query","description":"This is the unique identifier for the previous chat to filter by.","schema":{"type":"string"},"index$":5},{"name":"idAny","required":false,"in":"query","description":"Filter by multiple chat IDs. Provide as comma-separated values.","schema":{"type":"string"},"index$":6},{"name":"page","required":false,"in":"query","description":"This is the page number to return. Defaults to 1.","schema":{"minimum":1,"type":"number"},"index$":7},{"name":"sortOrder","required":false,"in":"query","description":"This is the sort order for pagination. Defaults to 'DESC'.","schema":{"enum":["ASC","DESC"],"type":"string"},"index$":8},{"name":"sortBy","required":false,"in":"query","description":"This is the column to sort by. Defaults to 'createdAt'.","schema":{"enum":["createdAt","duration","cost"],"type":"string"},"index$":9},{"name":"limit","required":false,"in":"query","description":"This is the maximum number of items to return. Defaults to 100.","schema":{"minimum":0,"maximum":1000,"type":"number"},"index$":10},{"name":"createdAtGt","required":false,"in":"query","description":"This will return items where the createdAt is greater than the specified value.","schema":{"format":"date-time","type":"string"},"index$":11},{"name":"createdAtLt","required":false,"in":"query","description":"This will return items where the createdAt is less than the specified value.","schema":{"format":"date-time","type":"string"},"index$":12},{"name":"createdAtGe","required":false,"in":"query","description":"This will return items where the createdAt is greater than or equal to the specified value.","schema":{"format":"date-time","type":"string"},"index$":13},{"name":"createdAtLe","required":false,"in":"query","description":"This will return items where the createdAt is less than or equal to the specified value.","schema":{"format":"date-time","type":"string"},"index$":14},{"name":"updatedAtGt","required":false,"in":"query","description":"This will return items where the updatedAt is greater than the specified value.","schema":{"format":"date-time","type":"string"},"index$":15},{"name":"updatedAtLt","required":false,"in":"query","description":"This will return items where the updatedAt is less than the specified value.","schema":{"format":"date-time","type":"string"},"index$":16},{"name":"updatedAtGe","required":false,"in":"query","description":"This will return items where the updatedAt is greater than or equal to the specified value.","schema":{"format":"date-time","type":"string"},"index$":17},{"name":"updatedAtLe","required":false,"in":"query","description":"This will return items where the updatedAt is less than or equal to the specified value.","schema":{"format":"date-time","type":"string"},"index$":18}]},"GET /chat/{id}":{"protocol":"http","parameters":[{"name":"id","required":true,"in":"path","schema":{"type":"string"},"index$":0}]},"DELETE /chat/{id}":{"protocol":"http","parameters":[{"name":"id","required":true,"in":"path","schema":{"type":"string"},"index$":0}]}})
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select


    // CREATE
    const chat_ref01_ent = client.Chat()
    let chat_ref01_data = setup.data.new.chat['chat_ref01']

    chat_ref01_data = (await chat_ref01_ent.create(chat_ref01_data)).data()
    assert(null != chat_ref01_data.id)


    // LIST
    const chat_ref01_match: any = {}

    const chat_ref01_list = (await chat_ref01_ent.list(chat_ref01_match)).map((e: any) => e.data())

    assert(!isempty(select(chat_ref01_list, { id: chat_ref01_data.id })))


    // LOAD
    const chat_ref01_match_dt0: any = {}
    chat_ref01_match_dt0.id = chat_ref01_data.id
    const chat_ref01_data_dt0 = (await chat_ref01_ent.load(chat_ref01_match_dt0)).data()
    assert(chat_ref01_data_dt0.id === chat_ref01_data.id)


    // REMOVE
    const chat_ref01_match_rm0: any = { id: chat_ref01_data.id }
    await chat_ref01_ent.remove(chat_ref01_match_rm0)
  

    // LIST
    const chat_ref01_match_rt0: any = {}

    const chat_ref01_list_rt0 = (await chat_ref01_ent.list(chat_ref01_match_rt0)).map((e: any) => e.data())

    assert(isempty(select(chat_ref01_list_rt0, { id: chat_ref01_data.id })))


  })
})



function basicSetup(extra?: any) {
  // TODO: fix test def options
  const options: any = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname, 
      '../../../../.sdk/test/entity/chat/ChatTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = VapiSDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['chat01','chat02','chat03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'VAPI_TEST_CHAT_ENTID': idmap,
    'VAPI_TEST_LIVE': 'FALSE',
    'VAPI_TEST_EXPLAIN': 'FALSE',
    'VAPI_APIKEY': '',
  })

  idmap = env['VAPI_TEST_CHAT_ENTID']

  const live = 'TRUE' === env.VAPI_TEST_LIVE

  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['VAPI_TEST_CHAT_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new VapiSDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
        apikey: env.VAPI_APIKEY,
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
      // last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey
      // and server values above and handed the SDK undefined. Harmless
      // while there was nothing in that object; not harmless now.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.VAPI_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
